name: Waka Readme

on:
  # for manual workflow trigger
  workflow_dispatch:
  schedule:
    # runs at 12 AM UTC (5:30 AM IST)
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master # this action name
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }} # optional if on profile readme
          ### meta
          API_BASE_URL: https://wakatime.com/api # optional
          REPOSITORY: YOUR_GITHUB_USERNAME/YOUR_REPOSITORY_NAME # optional
          ###mine
          SHOW_TOTAL: false
          SHOW_LINES_OF_CODE: true
          SHOW_PROFILE_VIEWS: false
          SHOW_COMMIT: true
          SHOW_LANGUAGE: true
          SHOW_SHORT_INFO: false
          SHOW_DAYS_OF_WEEK: false
          CODE_LANG: rust
          TIME_RANGE: all_time
          LANG_COUNT: 10
          SHOW_LANGUAGE_PER_REPO: false
          ### commit
          COMMIT_MESSAGE: Updated waka-readme graph with new metrics # optional
          TARGET_BRANCH: master # optional
          TARGET_PATH: README.md # optional
          COMMITTER_NAME: GitHubActionBot # optional
          COMMITTER_EMAIL: action-bot@github.com # optional
          AUTHOR_NAME: Ekrem05 # optional
          AUTHOR_EMAIL: YOUR@EMAIL.com # optional
          # you can populate email-id with secretes instead
